-- Players table to store character progress and state
CREATE TABLE IF NOT EXISTS public.players (
    wallet_address TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    level INTEGER DEFAULT 1 NOT NULL,
    gold INTEGER DEFAULT 50 NOT NULL,
    xp INTEGER DEFAULT 0 NOT NULL,
    items JSONB DEFAULT '[]'::jsonb NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Row Level Security (RLS) for players
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to players"
    ON public.players FOR SELECT USING (true);

CREATE POLICY "Allow users to insert their own profile"
    ON public.players FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow users to update their own profile"
    ON public.players FOR UPDATE USING (true);

-- Leaderboard table to track score/clears
CREATE TABLE IF NOT EXISTS public.leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT REFERENCES public.players(wallet_address) ON DELETE CASCADE NOT NULL,
    player_name TEXT NOT NULL,
    zone_clears INTEGER DEFAULT 0 NOT NULL,
    score INTEGER DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Row Level Security (RLS) for leaderboard
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to leaderboard"
    ON public.leaderboard FOR SELECT USING (true);

CREATE POLICY "Allow users to upsert their leaderboard records"
    ON public.leaderboard FOR ALL USING (true);
